# see https://searxng.org
use_default_settings: true

general:
  debug: false # Set to false for cleaner production logs on Render

search:
  formats:
    - html
    - json
    - csv
  api:
    json: true # Unlocks the JSON format so it won't throw an API error

server:

  secret_key: "${SEARXNG_SECRET_KEY}"
  limiter: false 
  image_proxy: true

ui:
  static_use_hash: true
